In [2]:
import pandas as pd
import numpy as np

In [3]:
air = pd.read_csv("C:\python\data\Air_Traffic_Passenger_Statistics.csv")

In [4]:
air

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090
...,...,...,...,...,...,...,...,...,...,...,...,...
18393,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Deplaned,Low Fare,International,A,4347
18394,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Enplaned,Low Fare,International,A,4228
18395,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,A,4292
18396,201803,WOW Air,WW,WOW Air,WW,International,Europe,Deplaned,Other,International,G,2699
18397,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,G,10

In [6]:
air.set_index(["Operating Airline","Activity Period"])

                                  Operating Airline IATA Code  \
Operating Airline Activity Period
ATA Airlines      200507                                   TZ
                  200507                                   TZ
                  200507                                   TZ
Air Canada        200507                                   AC
                  200507                                   AC
...                                                       ...
Volaris Airlines  201803                                   Y4
                  201803                                   Y4
WOW Air           201803                                   WW
                  201803                                   WW
                  201803                                   WW

                                  Published Airline  \
Operating Airline Activity Period
ATA Airlines      200507               ATA Airlines
                  200507               ATA Airlines
                  200507               ATA Airlines
Air Canada        200507                 Air Canada
                  200507                 Air Canada
...                                             ...
Volaris Airlines  201803           Volaris Airlines
                  201803           Volaris Airlines
WOW Air           201803                    WOW Air
                  201803                    WOW Air
                  201803                    WOW Air

                                  Published Airline IATA Code    GEO Summary  \
Operating Airline Activity Period
ATA Airlines      200507                                   TZ       Domestic
                  200507                                   TZ       Domestic
                  200507                                   TZ       Domestic
Air Canada        200507                                   AC  International
                  200507                                   AC  International
...                                                       ...            ...
Volaris Airlines  201803                                   Y4  International
                  201803                                   Y4  International
WOW Air           201803                                   WW  International
                  201803                                   WW  International
                  201803                                   WW  International

                                  GEO Region Activity Type Code  \
Operating Airline Activity Period
ATA Airlines      200507                  US           Deplaned
                  200507                  US           Enplaned
                  200507                  US     Thru / Transit
Air Canada        200507              Canada           Deplaned
                  200507              Canada           Enplaned
...                                      ...                ...
Volaris Airlines  201803              Mexico           Deplaned
                  201803              Mexico           Enplaned
WOW Air           201803              Europe           Enplaned
                  201803              Europe           Deplaned
                  201803              Europe           Enplaned

                                  Price Category Code       Terminal  \
Operating Airline Activity Period
ATA Airlines      200507                     Low Fare     Terminal 1
                  200507                     Low Fare     Terminal 1
                  200507                     Low Fare     Terminal 1
Air Canada        200507                        Other     Terminal 1
                  200507                        Other     Terminal 1
...                                               ...            ...
Volaris Airlines  201803                     Low Fare  International
                  201803                     Low Fare  International
WOW Air           201803                        Other  International
                  201803                        Other  International
                  201803                        Other  International

                                  Boarding Area  Passenger Count
Operating Airline Activity Period
ATA Airlines      200507                      B            27271
                  200507                      B            29131
                  200507                      B             5415
Air Canada        200507                      B            35156
                  200507                      B            34090
...                                         ...              ...
Volaris Airlines  201803                      A             4347
                  201803                      A             4228
WOW Air           201803                      A             4292
                  201803                      G             2699
                  201803                      G               10

[18398 rows x 10 columns]

In [7]:
air.reset_index()

,index,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count
0,0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271
1,1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131
2,2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415
3,3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156
4,4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18393,18393,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Deplaned,Low Fare,International,A,4347
18394,18394,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Enplaned,Low Fare,International,A,4228
18395,18395,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,A,4292
18396,18396,201803,WOW Air,WW,WOW Air,WW,International,Europe,Deplaned,Other,International,G,2699
18397,18397,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,G,10

In [11]:
air.set_index(["Activity Period","Operating Airline"], inplace =True)

In [12]:
air.sort_index(ascending=[True,False])

                                                         Operating Airline IATA Code  \
Activity Period Operating Airline
200507          WestJet Airlines                                                  WS
                WestJet Airlines                                                  WS
                Virgin Atlantic                                                   VS
                Virgin Atlantic                                                   VS
                United Airlines - Pre 07/01/2013                                  UA
...                                                                              ...
201803          Aeromexico                                                        AM
                Aer Lingus                                                        EI
                Aer Lingus                                                        EI
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O

                                                                                 Published Airline  \
Activity Period Operating Airline
200507          WestJet Airlines                                                  WestJet Airlines
                WestJet Airlines                                                  WestJet Airlines
                Virgin Atlantic                                                    Virgin Atlantic
                Virgin Atlantic                                                    Virgin Atlantic
                United Airlines - Pre 07/01/2013                  United Airlines - Pre 07/01/2013
...                                                                                            ...
201803          Aeromexico                                                              Aeromexico
                Aer Lingus                                                              Aer Lingus
                Aer Lingus                                                              Aer Lingus
                ABC Aerolineas S.A. de C.V. dba Interjet  ABC Aerolineas S.A. de C.V. dba Interjet
                ABC Aerolineas S.A. de C.V. dba Interjet  ABC Aerolineas S.A. de C.V. dba Interjet

                                                         Published Airline IATA Code  \
Activity Period Operating Airline
200507          WestJet Airlines                                                  WS
                WestJet Airlines                                                  WS
                Virgin Atlantic                                                   VS
                Virgin Atlantic                                                   VS
                United Airlines - Pre 07/01/2013                                  UA
...                                                                              ...
201803          Aeromexico                                                        AM
                Aer Lingus                                                        EI
                Aer Lingus                                                        EI
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O
                ABC Aerolineas S.A. de C.V. dba Interjet                          4O

                                                            GEO Summary  \
Activity Period Operating Airline
200507          WestJet Airlines                          International
                WestJet Airlines                          International
                Virgin Atlantic                           International
                Virgin Atlantic                           International
                United Airlines - Pre 07/01/2013               Domestic
...                                                                 ...
201803          Aeromexico                                International
                Aer Lingus                                International
                Aer Lingus                                International
                ABC Aerolineas S.A. de C.V. dba Interjet  International
                ABC Aerolineas S.A. de C.V. dba Interjet  International

                                                         GEO Region  \
Activity Period Operating Airline
200507          WestJet Airlines                             Canada
                WestJet Airlines                             Canada
                Virgin Atlantic                              Europe
                Virgin Atlantic                              Europe
                United Airlines - Pre 07/01/2013                 US
...                                                             ...
201803          Aeromexico                                   Mexico
                Aer Lingus                                   Europe
                Aer Lingus                                   Europe
                ABC Aerolineas S.A. de C.V. dba Interjet     Mexico
                ABC Aerolineas S.A. de C.V. dba Interjet     Mexico

                                                         Activity Type Code  \
Activity Period Operating Airline
200507          WestJet Airlines                                   Deplaned
                WestJet Airlines                                   Enplaned
                Virgin Atlantic                                    Deplaned
                Virgin Atlantic                                    Enplaned
                United Airlines - Pre 07/01/2013                   Deplaned
...                                                                     ...
201803          Aeromexico                                         Enplaned
                Aer Lingus                                         Deplaned
                Aer Lingus                                         Enplaned
                ABC Aerolineas S.A. de C.V. dba Interjet           Deplaned
                ABC Aerolineas S.A. de C.V. dba Interjet           Enplaned

                                                         Price Category Code  \
Activity Period Operating Airline
200507          WestJet Airlines                                       Other
                WestJet Airlines                                       Other
                Virgin Atlantic                                        Other
                Virgin Atlantic                                        Other
                United Airlines - Pre 07/01/2013                    Low Fare
...                                                                      ...
201803          Aeromexico                                             Other
                Aer Lingus                                             Other
                Aer Lingus                                             Other
                ABC Aerolineas S.A. de C.V. dba Interjet               Other
                ABC Aerolineas S.A. de C.V. dba Interjet               Other

                                                               Terminal  \
Activity Period Operating Airline
200507          WestJet Airlines                          International
                WestJet Airlines                          International
                Virgin Atlantic                           International
                Virgin Atlantic                           International
                United Airlines - Pre 07/01/2013             Terminal 3
...                                                                 ...
201803          Aeromexico                                International
                Aer Lingus                                International
                Aer Lingus                                International
                ABC Aerolineas S.A. de C.V. dba Interjet  International
                ABC Aerolineas S.A. de C.V. dba Interjet  International

                                                         Boarding Area  \
Activity Period Operating Airline
200507          WestJet Airlines                                     A
                WestJet Airlines                                     A
                Virgin Atlantic                                      A
                Virgin Atlantic                                      A
                United Airlines - Pre 07/01/2013                     E
...                                                                ...
201803          Aeromexico                                           A
                Aer Lingus                                           G
                Aer Lingus                                           G
                ABC Aerolineas S.A. de C.V. dba Interjet             A
                ABC Aerolineas S.A. de C.V. dba Interjet             A

                                                          Passenger Count
Activity Period Operating Airline
200507          WestJet Airlines                                     2480
                WestJet Airlines                                     2211
                Virgin Atlantic                                     11684
                Virgin Atlantic                                     10771
                United Airlines - Pre 07/01/2013                    58767
...                                                                   ...
201803          Aeromexico                                          12125
                Aer Lingus                                           7165
                Aer Lingus                                           6992
                ABC Aerolineas S.A. de C.V. dba Interjet             1090
                ABC Aerolineas S.A. de C.V. dba Interjet             1212

[18398 rows x 10 columns]

In [13]:
air.reset_index()

,Activity Period,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Activity Type Code,Price Category Code,Terminal,Boarding Area,Passenger Count
0,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Deplaned,Low Fare,Terminal 1,B,27271
1,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Enplaned,Low Fare,Terminal 1,B,29131
2,200507,ATA Airlines,TZ,ATA Airlines,TZ,Domestic,US,Thru / Transit,Low Fare,Terminal 1,B,5415
3,200507,Air Canada,AC,Air Canada,AC,International,Canada,Deplaned,Other,Terminal 1,B,35156
4,200507,Air Canada,AC,Air Canada,AC,International,Canada,Enplaned,Other,Terminal 1,B,34090
...,...,...,...,...,...,...,...,...,...,...,...,...
18393,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Deplaned,Low Fare,International,A,4347
18394,201803,Volaris Airlines,Y4,Volaris Airlines,Y4,International,Mexico,Enplaned,Low Fare,International,A,4228
18395,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,A,4292
18396,201803,WOW Air,WW,WOW Air,WW,International,Europe,Deplaned,Other,International,G,2699
18397,201803,WOW Air,WW,WOW Air,WW,International,Europe,Enplaned,Other,International,G,10

In [23]:
air.set_index(["Activity Period","Operating Airline","Activity Type Code"],inplace=True)

KeyError: "None of ['Activity Period', 'Operating Airline'] are in the columns"

In [28]:
air.reset_index(inplace = True)

In [29]:
air.set_index(["Activity Period","Operating Airline","Activity Type Code"],inplace=True)

In [30]:
air

                                                     Operating Airline IATA Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                                    TZ
                                  Enplaned                                    TZ
                                  Thru / Transit                              TZ
                Air Canada        Deplaned                                    AC
                                  Enplaned                                    AC
...                                                                          ...
201803          Volaris Airlines  Deplaned                                    Y4
                                  Enplaned                                    Y4
                WOW Air           Enplaned                                    WW
                                  Deplaned                                    WW
                                  Enplaned                                    WW

                                                     Published Airline  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                ATA Airlines
                                  Enplaned                ATA Airlines
                                  Thru / Transit          ATA Airlines
                Air Canada        Deplaned                  Air Canada
                                  Enplaned                  Air Canada
...                                                                ...
201803          Volaris Airlines  Deplaned            Volaris Airlines
                                  Enplaned            Volaris Airlines
                WOW Air           Enplaned                     WOW Air
                                  Deplaned                     WOW Air
                                  Enplaned                     WOW Air

                                                     Published Airline IATA Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                                    TZ
                                  Enplaned                                    TZ
                                  Thru / Transit                              TZ
                Air Canada        Deplaned                                    AC
                                  Enplaned                                    AC
...                                                                          ...
201803          Volaris Airlines  Deplaned                                    Y4
                                  Enplaned                                    Y4
                WOW Air           Enplaned                                    WW
                                  Deplaned                                    WW
                                  Enplaned                                    WW

                                                        GEO Summary  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                 Domestic
                                  Enplaned                 Domestic
                                  Thru / Transit           Domestic
                Air Canada        Deplaned            International
                                  Enplaned            International
...                                                             ...
201803          Volaris Airlines  Deplaned            International
                                  Enplaned            International
                WOW Air           Enplaned            International
                                  Deplaned            International
                                  Enplaned            International

                                                     GEO Region  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                   US
                                  Enplaned                   US
                                  Thru / Transit             US
                Air Canada        Deplaned               Canada
                                  Enplaned               Canada
...                                                         ...
201803          Volaris Airlines  Deplaned               Mexico
                                  Enplaned               Mexico
                WOW Air           Enplaned               Europe
                                  Deplaned               Europe
                                  Enplaned               Europe

                                                     Price Category Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                      Low Fare
                                  Enplaned                      Low Fare
                                  Thru / Transit                Low Fare
                Air Canada        Deplaned                         Other
                                  Enplaned                         Other
...                                                                  ...
201803          Volaris Airlines  Deplaned                      Low Fare
                                  Enplaned                      Low Fare
                WOW Air           Enplaned                         Other
                                  Deplaned                         Other
                                  Enplaned                         Other

                                                           Terminal  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned               Terminal 1
                                  Enplaned               Terminal 1
                                  Thru / Transit         Terminal 1
                Air Canada        Deplaned               Terminal 1
                                  Enplaned               Terminal 1
...                                                             ...
201803          Volaris Airlines  Deplaned            International
                                  Enplaned            International
                WOW Air           Enplaned            International
                                  Deplaned            International
                                  Enplaned            International

                                                     Boarding Area  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                       B
                                  Enplaned                       B
                                  Thru / Transit                 B
                Air Canada        Deplaned                       B
                                  Enplaned                       B
...                                                            ...
201803          Volaris Airlines  Deplaned                       A
                                  Enplaned                       A
                WOW Air           Enplaned                       A
                                  Deplaned                       G
                                  Enplaned                       G

                                                      Passenger Count
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Deplaned                      27271
                                  Enplaned                      29131
                                  Thru / Transit                 5415
                Air Canada        Deplaned                      35156
                                  Enplaned                      34090
...                                                               ...
201803          Volaris Airlines  Deplaned                       4347
                                  Enplaned                       4228
                WOW Air           Enplaned                       4292
                                  Deplaned                       2699
                                  Enplaned                         10

[18398 rows x 9 columns]

In [31]:
air.sort_index(ascending=[True,True,False])

                                                     Operating Airline IATA Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit                              TZ
                                  Enplaned                                    TZ
                                  Deplaned                                    TZ
                Air Canada        Enplaned                                    AC
                                  Deplaned                                    AC
...                                                                          ...
201803          Volaris Airlines  Enplaned                                    Y4
                                  Deplaned                                    Y4
                WOW Air           Enplaned                                    WW
                                  Enplaned                                    WW
                                  Deplaned                                    WW

                                                     Published Airline  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit          ATA Airlines
                                  Enplaned                ATA Airlines
                                  Deplaned                ATA Airlines
                Air Canada        Enplaned                  Air Canada
                                  Deplaned                  Air Canada
...                                                                ...
201803          Volaris Airlines  Enplaned            Volaris Airlines
                                  Deplaned            Volaris Airlines
                WOW Air           Enplaned                     WOW Air
                                  Enplaned                     WOW Air
                                  Deplaned                     WOW Air

                                                     Published Airline IATA Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit                              TZ
                                  Enplaned                                    TZ
                                  Deplaned                                    TZ
                Air Canada        Enplaned                                    AC
                                  Deplaned                                    AC
...                                                                          ...
201803          Volaris Airlines  Enplaned                                    Y4
                                  Deplaned                                    Y4
                WOW Air           Enplaned                                    WW
                                  Enplaned                                    WW
                                  Deplaned                                    WW

                                                        GEO Summary  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit           Domestic
                                  Enplaned                 Domestic
                                  Deplaned                 Domestic
                Air Canada        Enplaned            International
                                  Deplaned            International
...                                                             ...
201803          Volaris Airlines  Enplaned            International
                                  Deplaned            International
                WOW Air           Enplaned            International
                                  Enplaned            International
                                  Deplaned            International

                                                     GEO Region  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit             US
                                  Enplaned                   US
                                  Deplaned                   US
                Air Canada        Enplaned               Canada
                                  Deplaned               Canada
...                                                         ...
201803          Volaris Airlines  Enplaned               Mexico
                                  Deplaned               Mexico
                WOW Air           Enplaned               Europe
                                  Enplaned               Europe
                                  Deplaned               Europe

                                                     Price Category Code  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit                Low Fare
                                  Enplaned                      Low Fare
                                  Deplaned                      Low Fare
                Air Canada        Enplaned                         Other
                                  Deplaned                         Other
...                                                                  ...
201803          Volaris Airlines  Enplaned                      Low Fare
                                  Deplaned                      Low Fare
                WOW Air           Enplaned                         Other
                                  Enplaned                         Other
                                  Deplaned                         Other

                                                           Terminal  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit         Terminal 1
                                  Enplaned               Terminal 1
                                  Deplaned               Terminal 1
                Air Canada        Enplaned               Terminal 1
                                  Deplaned               Terminal 1
...                                                             ...
201803          Volaris Airlines  Enplaned            International
                                  Deplaned            International
                WOW Air           Enplaned            International
                                  Enplaned            International
                                  Deplaned            International

                                                     Boarding Area  \
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit                 B
                                  Enplaned                       B
                                  Deplaned                       B
                Air Canada        Enplaned                       B
                                  Deplaned                       B
...                                                            ...
201803          Volaris Airlines  Enplaned                       A
                                  Deplaned                       A
                WOW Air           Enplaned                       A
                                  Enplaned                       G
                                  Deplaned                       G

                                                      Passenger Count
Activity Period Operating Airline Activity Type Code
200507          ATA Airlines      Thru / Transit                 5415
                                  Enplaned                      29131
                                  Deplaned                      27271
                Air Canada        Enplaned                      34090
                                  Deplaned                      35156
...                                                               ...
201803          Volaris Airlines  Enplaned                       4228
                                  Deplaned                       4347
                WOW Air           Enplaned                       4292
                                  Enplaned                         10
                                  Deplaned                       2699

[18398 rows x 9 columns]